[advisories]
enabled = true
severity = "deny"

[licenses]
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "ISC"]
unlicensed = "deny"

[bans]
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
